app/models/conf_profile.py
from .. import db

class ConfProf (db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name
    desc
    cont

app/models/user.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from .. import db, login_manager


class User (UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100))
    password_hash = db.Column(db.String(128))

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, passwd):
        self.password_hash = generate_password_hash(passwd)
    
    def verify_password(self, passwd):
        return check_password_hash(self.password_hash, passwd)

    def __repr__(self):
        return '<User %r>' % self.username

@login_manager.user_loader
def load_user (user_id):
    return User.query.get(int(user_id))
    

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_login import LoginManager

from config import config

db = SQLAlchemy ()
bootstrap = Bootstrap ()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

from app.models.user import User


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    db.init_app(app)
    bootstrap.init_app(app)
    login_manager.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    return app

#from app import views, models.user

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, session
from flask_login import current_user
from io import UnsupportedOperation
import json

from . import main

from .. import db
from ..models.user import User
from ..auth.forms import UserAddForm, MainMenuForm



@main.route('/', methods=['GET', 'POST'])
def index():
    form = MainMenuForm ()
    if current_user.is_authenticated:
        return render_template ('user_index.html', form=form)
    return render_template ('anon_index.html')


@main.route('/user_add', methods=['GET', 'POST'])
def user_add():
    form = UserAddForm()
    if form.validate_on_submit():
        new_user = User(username = form.username.data)
        new_user.password = form.password.data
        form.password.data = ''
        return redirect (url_for('index'))
    return render_template ('user_add.html',
            form=form, name=session.get('name'))

app/templates/anon_index.html
{% extends "base.html" %}


{% block page_content %}
<div class="container">
    <div class="page-header">
        <h1>
	    Hello, Stranger!
	</h1>
    </div>
</div>
{% endblock %}

app/templates/base.html
{% extends "bootstrap/base.html" %}

{% block title %}Configuration{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle"
             data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
            </button>
            <a class="navbar-brand" href="/">Configuration</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
                <li><a href="{{ url_for('main.user_add') }}">Add User</a></li>
		<li>
		{% if current_user.is_authenticated %}
		    <a href="{{ url_for('auth.logout') }}">Logout</a>
		{% else %}
		    <a href="{{ url_for('auth.login') }}">Login</a> 
		{% endif %}
		</li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}


{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    {% block page_content %}{% endblock %}
</div>
{% endblock %}

app/templates/blank.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <div class="page-header">
        <h1>Hello!</h1>
    </div>
</div>
{% endblock %}

app/templates/user_add.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="container">
    <div class="page-header">
        <h1>Add User</h1>
    </div>
    <form method="POST" name="login">
        {{ wtf.quick_form(form) }}
    </form>
</div>
{% endblock %}

app/templates/user_index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block page_content %}
<div class="container">
    <div class="page-header">
        <h1>
	    Hello, {{ current_user.username }}!
	</h1>
    </div>
    <div class="col-md-4">
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}